config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  get 'games/:id/move/:move' => 'games#move'

  root 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  after_initialize :init
  serialize :moves, Array

  def init
    self.moves ||= []
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :move]
  before_action :set_move, only: [:move]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    chess_game = PGN::Game.new(@game.moves)
    @error = nil
    begin
      @fen = chess_game.positions.last.to_fen
      @fen = PGN::FEN.start if @game.moves.empty?
    rescue
      @fen = ''
      flash[:alert] = 'Invalid moves.'
      @error = 'Invalid moves.'
    end
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /games/1/move/e4.json
  def move
    @game.moves << @move
    chess_game = PGN::Game.new(@game.moves)
    @error = nil
    begin
      @fen = chess_game.positions.last.to_fen
    rescue
      @fen = ''
      flash[:alert] = 'Invalid move.'
      @error = 'Invalid move.'
    else
      @game.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    def set_move
      @move = params[:move]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      permitted_params = params.require(:game).permit(:moves)
      permitted_params[:moves] = JSON.parse(permitted_params[:moves])
      permitted_params
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Stayman Chess', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li<%= raw ' class="active"' if params[:controller].start_with? 'welcome' %>><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
          <li<%= raw ' class="active"' if params[:controller].start_with? 'games' %>><%= link_to 'Games', games_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to current_user.email, '#' %></li>
        </ul>
      <% else %>
        <%= form_for(:user, as: User, url: user_session_path, html: { class: 'navbar-form navbar-right', role: 'form' }) do |f| %>
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password' %>
          </div>

          <% if Devise.mappings[:user].rememberable? -%>
            <div class="form-group">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me, style: 'color:#ffffff;' %>
            </div>
          <% end -%>

          <%= f.submit "Log in", class: 'btn btn-success' %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success form-control' %>
        <% end %>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :moves %><br>
    <%= f.text_field :moves, size: 100 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<%= link_to 'New Game', new_game_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Game ID</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.id %></td>
        <td><%= game.created_at %></td>
        <td><%= game.updated_at %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<div id="board" style="width: 400px"></div>
<script>
  var game_id = '<%= @game.id %>';
</script>

<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stayman Chess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'nav' %>

<div class="container">

<% if notice %>
<div class="alert alert-warning" role="alert"><%= notice %></div>
<% end %>
<% if alert %>
<div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

<%= yield %>

</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Stayman Chess</h1>